"""Add historical tables

Revision ID: 54c7ab8212f9
Revises: e826449cda85
Create Date: 2024-11-12 23:45:23.059519+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c7ab8212f9'
down_revision = 'e826449cda85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trading_pair_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('volatility_short', sa.Float(), nullable=True),
    sa.Column('volatility_medium', sa.Float(), nullable=True),
    sa.Column('volatility_long', sa.Float(), nullable=True),
    sa.Column('ma7', sa.Float(), nullable=True),
    sa.Column('ma25', sa.Float(), nullable=True),
    sa.Column('ma99', sa.Float(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_middle', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('bb_width', sa.Float(), nullable=True),
    sa.Column('returns', sa.Float(), nullable=True),
    sa.Column('log_returns', sa.Float(), nullable=True),
    sa.Column('realized_volatility', sa.Float(), nullable=True),
    sa.Column('price_momentum', sa.Float(), nullable=True),
    sa.Column('volume_momentum', sa.Float(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trading_pair_id'], ['trading_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historical_metrics_pair_time', 'historical_metrics', ['trading_pair_id', 'timestamp', 'timeframe'], unique=False)
    op.create_table('market_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trading_pair_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('price_mean', sa.Float(), nullable=True),
    sa.Column('price_std', sa.Float(), nullable=True),
    sa.Column('price_skew', sa.Float(), nullable=True),
    sa.Column('price_kurtosis', sa.Float(), nullable=True),
    sa.Column('volatility_regime', sa.String(length=20), nullable=True),
    sa.Column('volatility_percentile', sa.Float(), nullable=True),
    sa.Column('volatility_zscore', sa.Float(), nullable=True),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('trend_strength', sa.Float(), nullable=True),
    sa.Column('trend_duration', sa.Integer(), nullable=True),
    sa.Column('market_regime', sa.String(length=20), nullable=True),
    sa.Column('market_score', sa.Float(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trading_pair_id'], ['trading_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_analysis_pair_time', 'market_analysis', ['trading_pair_id', 'timestamp', 'timeframe'], unique=False)
    op.drop_index('idx_kline_complete', table_name='kline_data')
    op.drop_index('idx_kline_interval', table_name='kline_data')
    op.drop_index('idx_kline_pair_interval', table_name='kline_data')
    op.drop_index('idx_kline_pair_time', table_name='kline_data')
    op.drop_index('idx_kline_timestamp', table_name='kline_data')
    op.drop_index('idx_kline_trading_pair', table_name='kline_data')
    op.drop_constraint('unique_kline_data', 'kline_data', type_='unique')
    op.create_index(op.f('ix_kline_data_timestamp'), 'kline_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kline_data_timestamp'), table_name='kline_data')
    op.create_unique_constraint('unique_kline_data', 'kline_data', ['trading_pair_id', 'timestamp', 'interval'])
    op.create_index('idx_kline_trading_pair', 'kline_data', ['trading_pair_id'], unique=False)
    op.create_index('idx_kline_timestamp', 'kline_data', ['timestamp'], unique=False)
    op.create_index('idx_kline_pair_time', 'kline_data', ['trading_pair_id', 'timestamp'], unique=False)
    op.create_index('idx_kline_pair_interval', 'kline_data', ['trading_pair_id', 'interval'], unique=False)
    op.create_index('idx_kline_interval', 'kline_data', ['interval'], unique=False)
    op.create_index('idx_kline_complete', 'kline_data', ['is_complete'], unique=False)
    op.drop_index('idx_market_analysis_pair_time', table_name='market_analysis')
    op.drop_table('market_analysis')
    op.drop_index('idx_historical_metrics_pair_time', table_name='historical_metrics')
    op.drop_table('historical_metrics')
    # ### end Alembic commands ###